urls:
- http://www.reddit.com/r/NSFW_HTML5/.rss
- http://www.reddit.com/r/pornvids/.rss
- http://www.reddit.com/r/gonewild/.rss
- http://www.reddit.com/r/NSFW_GIF/.rss
- http://www.reddit.com/r/NSFW411/.rss
- http://www.reddit.com/r/TikTokNSFW/.rss
- http://www.reddit.com/r/TikTokThots/.rss
